# Generated by Django 5.2.6 on 2025-09-16 21:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
